// guidance.ts — the instruction ("template + guardrails") the hook injects when it denies
// a commit / PR-create that lacks a why-block.
//
// This text is what the LIVE model reads on the denial and acts on: it composes the
// forward-only block from the session's real deliberation and re-runs the command. The
// hook itself never authors the block — it only asks for it. The guidance is surface-
// aware (PR body vs commit message use different delimiters and a different attribution
// form), tells the model to size the block to the change and lead with the non-obvious,
// and carries a visible attribution so a reviewer can tell where the block came from.

import {
  renderBlock,
  delimiters,
  HEADINGS,
  PRIMITIVES,
  isEmptyBlock,
  type Surface,
  type WhyPrimitives,
} from './template.js';
import { SKIP_TOKEN } from './repoConfig.js';

// Re-export so existing importers (hook.ts) keep a single import site for Surface.
export type { Surface } from './template.js';

const PACKAGE_URL = 'https://github.com/backthread/add-reasoning-to-prs';

interface SurfaceCopy {
  moment: string;
  where: string;
}

function surfaceCopy(surface: Surface): SurfaceCopy {
  return surface === 'pr'
    ? {
        moment: 'this pull request is opened',
        where: 'the pull request description (the --body / --body-file text)',
      }
    : {
        moment: 'this commit lands on the default branch',
        where: 'the commit message body',
      };
}

// The visible attribution that opens/closes the block, INSIDE the markers (so it is
// detected for idempotency and stripped by the ingestion-side self-ingestion skip, never
// re-ingested). Markdown (a linked caption) on the PR surface; PLAIN TEXT on the commit
// surface — a commit message doesn't render markdown, HTML, or links.
function attributionHeader(surface: Surface): string {
  return surface === 'pr'
    ? `## Reasoning\n<sub>written by the agent in-session via [\`backthread/add-reasoning-to-prs\`](${PACKAGE_URL})</sub>`
    : 'reasoning · written in-session via backthread/add-reasoning-to-prs';
}

function attributionFooter(surface: Surface): string {
  return surface === 'pr'
    ? `<sub>↳ generated by [\`backthread/add-reasoning-to-prs\`](${PACKAGE_URL}) · an open-source Claude Code hook · edit or delete freely</sub>`
    : 'generated by backthread/add-reasoning-to-prs — an open-source Claude Code hook; edit or delete freely';
}

/** A filled-in-shape example of the block for a surface: the canonical template (so the
 * guidance can't drift from the real render) with the visible attribution spliced INSIDE
 * the markers. This shows the SUBSTANTIAL-block form; the prose explains scaling down. */
function exampleBlock(surface: Surface): string {
  const { open, close } = delimiters(surface);
  const placeholder = ['<one concise line — omit this whole section if it does not apply>'];
  const rendered = renderBlock(surface, {
    decisions: placeholder,
    assumptions: placeholder,
    tradeoffs: placeholder,
    limitations: placeholder,
    // Renders only on the PR surface (renderBlock drops it on the commit surface).
    followups: placeholder,
  });
  // renderBlock wraps the body in the markers; lift the body out and re-wrap it with the
  // attribution inside the same markers.
  const body = rendered.slice(open.length, rendered.length - close.length).trim();
  return [open, attributionHeader(surface), '', body, '', attributionFooter(surface), close].join(
    '\n',
  );
}

/** Render accumulated (earlier-session) primitives as a plain, readable list. */
function renderAccumulated(p: WhyPrimitives): string {
  const lines: string[] = [];
  // Intentionally the four core PRIMITIVES only — the scratchpad never banks the PR-only
  // `followups` (scratch.coercePrimitives loops PRIMITIVES), so an accumulated set can't
  // carry one. If follow-ups ever become bankable, widen this to ALL_PRIMITIVES.
  for (const key of PRIMITIVES) {
    const items = (p[key] ?? []).filter(Boolean);
    if (items.length === 0) continue;
    lines.push(`${HEADINGS[key]}:`);
    for (const it of items) lines.push(`- ${it}`);
  }
  return lines.join('\n');
}

/**
 * Build the guidance for a surface. The SAME text is used for both the
 * `permissionDecisionReason` (the reliable floor, honored on every Claude Code version)
 * and `additionalContext` (a progressive enhancement), so the model always sees it.
 *
 * When `accumulated` primitives are supplied (banked earlier on this branch, possibly by
 * a different session), they're surfaced so the block can cover the WHOLE branch.
 */
export function buildGuidance(surface: Surface, accumulated?: WhyPrimitives): string {
  const c = surfaceCopy(surface);
  const isPr = surface === 'pr';
  const earlier =
    accumulated && !isEmptyBlock(accumulated)
      ? `\n\nEarlier work on this branch (possibly a different session) already recorded these — fold the still-relevant points into the block instead of pasting them, and drop anything now stale:\n\n${renderAccumulated(accumulated)}\n`
      : '';
  // The Recommended-follow-ups primitive renders on the PR surface only. A commit message is
  // immutable once pushed and has no backlog home, so a forward-looking to-do has no place there.
  const followupsBullet = isPr
    ? `\n- Recommended follow-ups — a concrete next step your reasoning surfaced that a reviewer could NOT get from this diff alone. Most PRs have none.`
    : '';
  const followupsGuidance = isPr
    ? `

Recommended follow-ups (pull requests only):
- Add this section ONLY for a follow-up that your in-session reasoning surfaced AND a reviewer could not see from this PR's diff alone. Prefer a consequence in another file, another repository, or another service.
- Precision over coverage. If a careful reviewer could also reach the item by reading this diff, drop it. Most PRs have no follow-up. An empty section is the normal, correct outcome.
- Exclude anything a normal code review, a linter, or CI already catches. This is not a review checklist.
- Name the exact repository, file, or function only when it appeared in this session. Never guess a path. A wrong path is worse than none.
- One risk has one home. Keep the inline "Check: ..." tail on a risk by default; only when that action is a cross-boundary follow-up you are promoting into this section, move it here and remove the "Check: ..." tail there — so the same action is never written twice.`
    : '';
  return `add-reasoning-to-prs: before ${c.moment}, add a short, forward-only "why" block to ${c.where}, then re-run the command.${earlier}

Write the block ONLY from what you actually decided in THIS session — never invent. Use only the sections that apply:

- Decisions — the choices you made and why (not what changed; the diff already shows that).
- Assumptions — what you took as given that a reviewer should confirm.
- Trade-offs — what you knowingly gave up, and the option you rejected.
- Limitations — known gaps or risks you are deliberately leaving.${followupsBullet}

How much to write:
- Size the block to the change. Most PRs need one to three lines, not four full sections. A small or mechanical PR gets one line, or none.
- Lead with the one point a reviewer could NOT get from the diff — the risk you knowingly took, a default you reversed, a hidden constraint. Cut the obvious lines that ride along with it. One sharp point beats three restatements.
- Keep that one genuinely useful non-obvious point even on a small PR. Do not go silent just to look disciplined.
- If the session had no real decision, add no block. An empty block is the correct answer for a routine change.

Be honest:
- Forward-only: capture what the diff can't show — the why, and the risks knowingly taken. Never summarize the changes.
- Every line must trace to a real decision in this session. If the reason was never stated, drop the line — do not guess it.
- Never restate the diff ("added X", "refactored Y"), and never pad with filler ("improves code quality", "various cleanups").
- Write a caveat as a claim plus its silent consequence: "Assumes X; if X is wrong, Y breaks." A caveat with no named consequence is filler — cut it. End a risk with a short action, e.g. "Check: review both lists".${followupsGuidance}

Write it plainly — the reviewer may not be a native English speaker:
- One idea per sentence; prefer several short sentences over one long one with stacked clauses.
- Use plain words, not idioms or metaphors — say the literal thing ("follow foreign keys", not "hop the graph"; "turn it off", not "kill-switch"). Keep real names (tables, flags, functions, endpoints, keys) exactly — never trade a concrete name for a vague one.
- Avoid "X → Y" / "X: Y" logic shorthand; write it as a sentence (a relationship example like \`a\` → \`b\` is fine).
- Plain, factual, senior-engineer voice. No self-praise or marketing words (no "elegant", "robust", "clean", "seamless", "improves quality"). Say only what you decided and what is risky.

Format:
- Keep the headings in the order shown; include only the non-empty ones.
- Wrap the block EXACTLY between the two markers below so it is detected and left untouched on later runs.
- Add a visible attribution INSIDE the markers, scaled to the block. A substantial block uses the full attribution shown below (the heading/opening line plus the small closing note); a one- or two-line block uses only a single compact attribution line. Never a banner.

${exampleBlock(surface)}

Self-check BEFORE you write — a quick grounded pass, no tools or network needed:
- Take each candidate line and name the specific point in THIS session where that decision, assumption, trade-off, or limitation actually came up. If you can't point to one, delete the line.
- If nothing survives, there is no block to add: re-run your original command unchanged, or add ${SKIP_TOKEN} to it to opt out explicitly. Never manufacture filler — an empty block is the correct outcome for a session that didn't deliberate.

Otherwise, re-run your original command with the surviving block included in ${c.where}.`;
}

/**
 * The best-effort nudge injected (as non-blocking additionalContext) on a feature-branch
 * commit: bank this session's why to the branch scratchpad so the eventual PR — even one
 * opened by a different session — can fold it in.
 */
export function buildScratchNudge(): string {
  return `add-reasoning-to-prs: you're committing on a feature branch, so this commit isn't touched. If this chunk of work involved a notable decision, assumption, trade-off, or limitation, bank it now — the eventual PR's why-block will fold it in, even if a different session opens the PR:

  add-reasoning-to-prs scratch add --json '{"decisions":["..."],"tradeoffs":["..."]}'

It's 100% local (nothing is committed) and stores only the why, never code. Skip it if there was nothing notable this time.`;
}
